# Generated by Django 3.2.12 on 2023-04-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=50)),
                ('subcode', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
            ],
        ),
    ]
