# Generated by Django 3.2.12 on 2023-04-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='departmentName',
            field=models.CharField(default='nodept', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='semesterNo',
            field=models.IntegerField(default=0),
        ),
    ]
