# Generated by Django 3.2.12 on 2023-04-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20230424_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='departmentName',
            field=models.CharField(choices=[('BCS', 'ComputerScience and Engineering '), ('BIT', 'Information Technology'), ('BET', 'Electronics and Telecommunication  Engineering'), ('BEC', 'Electrical Engineering'), ('BIN', ' Instrumentation Engineering'), ('BME', 'Mechanical Engineering'), ('BCV', 'Civil Engineering'), ('BPR', 'Production Engineering'), ('BCH', 'Chemical Engineering'), ('BTX', 'Textile Engineering')], default='nodept', max_length=100),
        ),
    ]
