# Generated by Django 3.2.12 on 2023-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=40)),
                ('departmentId', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Markss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem1', models.IntegerField(default=True)),
                ('sem2', models.IntegerField(default=True)),
                ('sem3', models.IntegerField(default=True)),
                ('sem4', models.IntegerField(default=True)),
                ('sem5', models.IntegerField(default=True)),
                ('sem6', models.IntegerField(default=True)),
                ('sem7', models.IntegerField(default=True)),
                ('sem8', models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesterNo', models.IntegerField()),
                ('semesterId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=True, max_length=40)),
                ('RegNo', models.CharField(default=True, max_length=40)),
                ('Year_of_Joining', models.DateField(default=True, max_length=40)),
                ('Passing_year', models.DateField()),
                ('Email', models.EmailField(default=True, max_length=254)),
                ('Phone_Number', models.IntegerField(default=True)),
                ('Address', models.TextField(default=True, max_length=120)),
                ('No_of_Transcript_R', models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjecttName', models.CharField(max_length=40)),
                ('semesterId', models.IntegerField()),
                ('departmentId', models.IntegerField()),
            ],
        ),
    ]
