# Generated by Django 3.2.12 on 2023-04-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(default=True, max_length=40, null=True),
        ),
    ]
