# Generated by Django 3.2.12 on 2023-04-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.TextField(default=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(default=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='No_of_Transcript_R',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Passing_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Phone_Number',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='RegNo',
            field=models.CharField(default=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Year_of_Joining',
            field=models.DateField(default=True, max_length=40, null=True),
        ),
    ]
