# Generated by Django 3.2.12 on 2023-04-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230422_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markss',
            name='sem1',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='markss',
            name='sem2',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='markss',
            name='sem3',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='markss',
            name='sem4',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='markss',
            name='sem5',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='markss',
            name='sem6',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='markss',
            name='sem7',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='markss',
            name='sem8',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
