# Generated by Django 3.2.12 on 2023-04-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230422_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subCode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
